<!doctype html>
<html>
    <head>
     <meta charset="UTF-8" />
     <title>فروشگاه ایرانیان</title>  
     <link href="style.css" rel="stylesheet" type="text/css" />
     <style type="text/css">
        <!==
        .set_style_link {
            text-decoration:none;
            font-weight:bold;
        }
        ==>
     </style>
    </head>
    <body>
        <div class="divTable">
            <div class="divTableRow">
                <div class="divTableCell">
                    <header class="divTable">
                        <div class="divTableRow">
                            <div class="divTableCell"></div>
                        </div>
                    </header>
                    <nav class="divTable">
                        <ul class="divTableRow">
                            <li class="divTableCell"<a class="set_style_link" href="index.php">صفحه اصلی</a></li>
                            <li class="divTableCell"<a class="set_style_link" href="index.php">عضویت در سایت</a></li>
                            <li class="divTableCell"<a class="set_style_link" href="index.php">ورود به سایت</a></li>
                            <li class="divTableCell"<a class="set_style_link" href="index.php">درباره ما</a></li>
                            <li class="divTableCell"<a class="set_style_link" href="index.php">ارتباط با ما</a></li>
                        </ul>
                    </nav>
                    <section class="divTable">
                    <section class="divTableRow">
                    <aside class="divTableCell" style="width:25%;">بخش امکانات سایت</aside>
                    <section class="divTableCell" style="width: 75%;">
                    </section>
                    </section>
                    </section>
                    <footer class="divTable">
                        <section class="divTableRow">
                            <article class="divTableCell">مالکیت مادی و معنوی سایت</article>
                        </section>
                    </footer>
                </div>
            </div>
        </div>
    </body>
</html>